const ENV = {
  LOCAL: 'local',
  DEVELOPMENT: 'development',
  STAGING: 'staging',
  PRODUCTION: 'production',
}

export { ENV }

const CATEGORY_TYPES = {
  ARTICLE: 'ARTICLE',
  ACTIVITY: 'ACTIVITY',
}

const STATES = {
  DRAFT: 'DRAFT',
  IN_REVIEW: 'IN_REVIEW',
  READY: 'READY',
  PUBLISHED: 'PUBLISHED',
  REWORK: 'REWORK',
  ARCHIVED: 'ARCHIVED',
  DELETED: 'DELETED',
}

const ARTICLE_STATES = STATES

export { CATEGORY_TYPES, ARTICLE_STATES }
